amr:
    # Publish all joint states -----------------------------------
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

    # Position Controllers motor right--------------------------------
    base_link_driving_wheel_M1_joint_velocity_controller:
    #base_link_driving_wheel_M1_joint_velocity_controller:
      #type: effort_controllers/JointPositionController
      type: velocity_controllers/JointVelocityController
      joint: base_link_driving_wheel_M1_joint
      pid: {p: 1.0, i: 1.0, d: 0.0}
    # To add more just add them here as the first one

    # Position Controllers motor left--------------------------------
    #type: effort_controllers/JointPositionController
    base_link_driving_wheel_M2_joint_velocity_controller:
      type: velocity_controllers/JointVelocityController
      joint: base_link_driving_wheel_M2_joint
      pid: {p: 1.0, i: 1.0, d: 0.0}
    # To add more just add them here as the first one